version: "3.7"

services:
    db_postgres:
        image: postgres:12
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - ./.envs/.postgres
        networks:
            - net-app

    backend:
        build: ../backend
        ports:
            - 8000:8000
        env_file:
            - ./.envs/.env-back
        depends_on:
            - db_postgres
        networks:
            - net-app

    frontend:
        build: ../frontend
        ports:
            - 3000:3000
        networks:
            - net-app
    
volumes:
    postgres_data:
networks:
    net-app:
