version: "3.7"

services:
    web-service:
        image: nginx:1.20-alpine
        restart: always
        ports:
            - 5678:80
        volumes:
            - ../static:/usr/share/nginx/html


