name: Publish Docker image

on:
  push:
    paths:
      - '**.html'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lucassalse/craftech-interview
          tag_with_ref: true
          tag_with_sha: true
          tags: latest, ${{ github.sha }}